In [1]:
import pandas as pd

In [2]:
video_model = pd.read_csv('video_model.csv.gz', compression='gzip', header=0, sep=',', quotechar='"', error_bad_lines=False)

In [3]:
video_model

,timestamp,user_id,device_id,session_uuid,Entity,viewed_pct,viewed_secs,duration_secs,content_name,provider,station,season,episode,type,rights_type
0,2018-06-11T17:16:52.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,2c35e72e617597be0feecee9ad47290383b0b0f0,6.625862e+18,2,82,4306,Pose,FX,NaN,1,2,On-Demand,TVE
1,2018-06-11T17:14:00.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,2c35e72e617597be0feecee9ad47290383b0b0f0,6.625862e+18,0,0,5220,Pose,FX,NaN,1,1,On-Demand,T6
2,2018-06-11T15:56:22.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,cff4031917c5ad85998368d6e99b56bd93f0fa47,5.213097e+18,66,1195,1800,FliporFlop,NaN,HGTVD,6,6,Live,TVE
3,2018-06-11T17:00:01.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,cff4031917c5ad85998368d6e99b56bd93f0fa47,6.652018e+18,100,3600,3600,DaysofourLives,NaN,NBCHD,53,180,Live,TVE
4,2018-06-11T17:14:15.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,2c35e72e617597be0feecee9ad47290383b0b0f0,6.625862e+18,0,5,4762,Pose,FX,NaN,1,1,On-Demand,TVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177066,2018-07-01T14:48:10.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,fb0b3cbbac50b50a0ea02288e4f797895f6e539f,ea52c62656fd26e8277926b08a52f08c0dfecf71,4.892220e+18,19,1682,9000,CopaMundialdelaFIFA2018,NaN,KSTSD,0,0,Live,T6
177067,2018-06-21T14:00:01.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,fb0b3cbbac50b50a0ea02288e4f797895f6e539f,6e752826fbabde81d69a0dea7424a05901f3ff0c,4.892220e+18,33,2944,9000,CopaMundialdelaFIFA2018,NaN,KSTSD,0,0,Live,T6
177068,2018-06-23T12:19:16.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,fb0b3cbbac50b50a0ea02288e4f797895f6e539f,cf81bb83fe78fc94a6405ee5ba2479f0412f467e,4.892220e+18,0,0,9000,CopaMundialdelaFIFA2018,NaN,KSTSD,0,0,Live,T6
177069,2018-09-23T20:10:35.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,0bfd18942eabbec05bb9a71aa0a1a165ae78a600,6c68271c4feb846fcfef8d8d939bdd0db525c0fd,7.371329e+18,89,10944,12300,NFLFootball-49ers@Chiefs,NaN,KTVUD,0,0,Live,TVE
177070,2018-09-23T17:08:10.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,0bfd18942eabbec05bb9a71aa0a1a165ae78a600,6c68271c4feb846fcfef8d8d939bdd0db525c0fd,7.371329e+18,4,489,12300,NFLFootball-49ers@Chiefs,NaN,KTVUD,0,0,Live,TVE

In [32]:
session_model = pd.read_csv('session_model.csv.gz', compression='gzip', header=0, sep=',', quotechar='"', error_bad_lines=False)

In [33]:
session_model

,timestamp,user_id,device_id,session_uuid,birth_date,device_type,pages_viewed,session_number
0,2018-06-29T22:41:20.000Z,21D23C29-3BC9-4BB3-9C23-7505BD22FDF8,d664d24fea7ee368e07d4aa548d0a7df5365966f,1abcceb8a1038d6e450128a5924d4670c373cc02,1483901689,iPad Pro (12.9 inch),0,40
1,2018-08-30T01:02:45.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,360853b3cb4a20973fa8e44a3c6aa8b5dfe60296,1477611249,iPhone 6S Plus,0,229
2,2018-06-25T14:54:15.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,b95154bc61c50150c23f9a9d721383fd8a736ef2,1477611249,iPhone 6S Plus,2,217
3,2018-06-20T01:43:38.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,4ee17538aae8d77ff8aa0f75740deed78e7d26ce,1477611249,iPhone 6S Plus,6,216
4,2018-06-11T17:05:44.000Z,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,cff4031917c5ad85998368d6e99b56bd93f0fa47,1477611249,iPhone 6S Plus,6,212
...,...,...,...,...,...,...,...,...
90959,2018-06-25T13:30:41.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,fb0b3cbbac50b50a0ea02288e4f797895f6e539f,6690dbd84a9ee0559646aea23a320e0388810ae6,1471092105,iPad mini,2,25
90960,2018-08-17T19:52:19.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,cf356cddfd754e370f8e00d3ddde5180321fae25,82990b9e6a51e4401bf039e9018eb4ca9327886b,1492741108,iPhone 6S,4,97
90961,2018-07-10T19:49:39.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,f01b70859814a84c7008f52e723ac91c57c4522d,ed81863be8d6738f7654b32d0b9d4042060682f1,1529081570,iPhone 6S,0,11
90962,2018-06-18T21:10:27.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,cf356cddfd754e370f8e00d3ddde5180321fae25,12577af5619b98c18f8e50e64e75af1df357b7bf,1492741108,iPhone 6S,3,84
90963,2018-06-27T14:35:20.000Z,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,f01b70859814a84c7008f52e723ac91c57c4522d,28147258eed4a9fc7e3696271c3eb34dab2de051,1529081570,iPhone 6S,2,5

In [34]:
session_model['session_ts'] = pd.to_datetime(session_model['timestamp'])

session_model['birth_date'] = pd.to_datetime(session_model['birth_date'], unit='s')

In [35]:
session_model = session_model.drop(columns=['timestamp'])

In [36]:
session_model.dtypes

user_id                        object
device_id                      object
session_uuid                   object
birth_date             datetime64[ns]
device_type                    object
pages_viewed                    int64
session_number                  int64
session_ts        datetime64[ns, UTC]
dtype: object

In [37]:
session_model

,user_id,device_id,session_uuid,birth_date,device_type,pages_viewed,session_number,session_ts
0,21D23C29-3BC9-4BB3-9C23-7505BD22FDF8,d664d24fea7ee368e07d4aa548d0a7df5365966f,1abcceb8a1038d6e450128a5924d4670c373cc02,2017-01-08 18:54:49,iPad Pro (12.9 inch),0,40,2018-06-29 22:41:20+00:00
1,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,360853b3cb4a20973fa8e44a3c6aa8b5dfe60296,2016-10-27 23:34:09,iPhone 6S Plus,0,229,2018-08-30 01:02:45+00:00
2,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,b95154bc61c50150c23f9a9d721383fd8a736ef2,2016-10-27 23:34:09,iPhone 6S Plus,2,217,2018-06-25 14:54:15+00:00
3,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,4ee17538aae8d77ff8aa0f75740deed78e7d26ce,2016-10-27 23:34:09,iPhone 6S Plus,6,216,2018-06-20 01:43:38+00:00
4,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,cff4031917c5ad85998368d6e99b56bd93f0fa47,2016-10-27 23:34:09,iPhone 6S Plus,6,212,2018-06-11 17:05:44+00:00
...,...,...,...,...,...,...,...,...
90959,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,fb0b3cbbac50b50a0ea02288e4f797895f6e539f,6690dbd84a9ee0559646aea23a320e0388810ae6,2016-08-13 12:41:45,iPad mini,2,25,2018-06-25 13:30:41+00:00
90960,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,cf356cddfd754e370f8e00d3ddde5180321fae25,82990b9e6a51e4401bf039e9018eb4ca9327886b,2017-04-21 02:18:28,iPhone 6S,4,97,2018-08-17 19:52:19+00:00
90961,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,f01b70859814a84c7008f52e723ac91c57c4522d,ed81863be8d6738f7654b32d0b9d4042060682f1,2018-06-15 16:52:50,iPhone 6S,0,11,2018-07-10 19:49:39+00:00
90962,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,cf356cddfd754e370f8e00d3ddde5180321fae25,12577af5619b98c18f8e50e64e75af1df357b7bf,2017-04-21 02:18:28,iPhone 6S,3,84,2018-06-18 21:10:27+00:00
90963,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,f01b70859814a84c7008f52e723ac91c57c4522d,28147258eed4a9fc7e3696271c3eb34dab2de051,2018-06-15 16:52:50,iPhone 6S,2,5,2018-06-27 14:35:20+00:00

In [38]:
import datetime

In [47]:
session_model['session_date'] = session_model['session_ts'].dt.floor('D')
session_model['session_week'] = session_model['session_ts'].dt.to_period('W')
session_model['session_month'] = session_model['session_ts'].dt.to_period('M')

/usr/local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py:1102: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  UserWarning,

In [48]:
session_model

,user_id,device_id,session_uuid,birth_date,device_type,pages_viewed,session_number,session_ts,session_date,session_week,session_month
0,21D23C29-3BC9-4BB3-9C23-7505BD22FDF8,d664d24fea7ee368e07d4aa548d0a7df5365966f,1abcceb8a1038d6e450128a5924d4670c373cc02,2017-01-08 18:54:49,iPad Pro (12.9 inch),0,40,2018-06-29 22:41:20+00:00,2018-06-29 00:00:00+00:00,2018-06-25/2018-07-01,2018-06
1,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,360853b3cb4a20973fa8e44a3c6aa8b5dfe60296,2016-10-27 23:34:09,iPhone 6S Plus,0,229,2018-08-30 01:02:45+00:00,2018-08-30 00:00:00+00:00,2018-08-27/2018-09-02,2018-08
2,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,b95154bc61c50150c23f9a9d721383fd8a736ef2,2016-10-27 23:34:09,iPhone 6S Plus,2,217,2018-06-25 14:54:15+00:00,2018-06-25 00:00:00+00:00,2018-06-25/2018-07-01,2018-06
3,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,4ee17538aae8d77ff8aa0f75740deed78e7d26ce,2016-10-27 23:34:09,iPhone 6S Plus,6,216,2018-06-20 01:43:38+00:00,2018-06-20 00:00:00+00:00,2018-06-18/2018-06-24,2018-06
4,7IPz1LiHSIlti/6B+2bGc2FduMtUS7XPIpupqbsWj4I=,fc9e397059739c9e0d33293f6772b769422748d0,cff4031917c5ad85998368d6e99b56bd93f0fa47,2016-10-27 23:34:09,iPhone 6S Plus,6,212,2018-06-11 17:05:44+00:00,2018-06-11 00:00:00+00:00,2018-06-11/2018-06-17,2018-06
...,...,...,...,...,...,...,...,...,...,...,...
90959,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,fb0b3cbbac50b50a0ea02288e4f797895f6e539f,6690dbd84a9ee0559646aea23a320e0388810ae6,2016-08-13 12:41:45,iPad mini,2,25,2018-06-25 13:30:41+00:00,2018-06-25 00:00:00+00:00,2018-06-25/2018-07-01,2018-06
90960,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,cf356cddfd754e370f8e00d3ddde5180321fae25,82990b9e6a51e4401bf039e9018eb4ca9327886b,2017-04-21 02:18:28,iPhone 6S,4,97,2018-08-17 19:52:19+00:00,2018-08-17 00:00:00+00:00,2018-08-13/2018-08-19,2018-08
90961,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,f01b70859814a84c7008f52e723ac91c57c4522d,ed81863be8d6738f7654b32d0b9d4042060682f1,2018-06-15 16:52:50,iPhone 6S,0,11,2018-07-10 19:49:39+00:00,2018-07-10 00:00:00+00:00,2018-07-09/2018-07-15,2018-07
90962,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,cf356cddfd754e370f8e00d3ddde5180321fae25,12577af5619b98c18f8e50e64e75af1df357b7bf,2017-04-21 02:18:28,iPhone 6S,3,84,2018-06-18 21:10:27+00:00,2018-06-18 00:00:00+00:00,2018-06-18/2018-06-24,2018-06
90963,TimWK7xYnQCItvJVe/QUMFw5Ufyps4Ykq5YTD47wIQE=,f01b70859814a84c7008f52e723ac91c57c4522d,28147258eed4a9fc7e3696271c3eb34dab2de051,2018-06-15 16:52:50,iPhone 6S,2,5,2018-06-27 14:35:20+00:00,2018-06-27 00:00:00+00:00,2018-06-25/2018-07-01,2018-06

In [49]:
users_per_day = session_model.groupby('session_date')['user_id'].count()

In [50]:
users_per_day

session_date
2018-06-01 00:00:00+00:00    543
2018-06-02 00:00:00+00:00    673
2018-06-03 00:00:00+00:00    671
2018-06-04 00:00:00+00:00    867
2018-06-05 00:00:00+00:00    779
                            ...
2018-09-26 00:00:00+00:00    666
2018-09-27 00:00:00+00:00    358
2018-09-28 00:00:00+00:00    515
2018-09-29 00:00:00+00:00    738
2018-09-30 00:00:00+00:00    845
Name: user_id, Length: 122, dtype: int64